dist: xenial
language: cpp
compiler:
- gcc
before_install:
- sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
- sudo apt-get update -qq
- sudo apt-get install libgnutls28-dev
- sudo apt-get install build-essential pkg-config libcurl3-gnutls-dev libc6-dev libevent-dev
  m4 g++-multilib autoconf libtool ncurses-dev unzip git python zlib1g-dev wget bsdmainutils
  automake libssl-dev libprotobuf-dev protobuf-compiler libdb++-dev ntp ntpdate
script:
- "./zcutil/build.sh -j 5"
notifications:
  irc:
    channels:
    - chat.freenode.net#komodoplatform
    template:
    - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
    - 'Alt Message : %{repository_slug} - (%{commit} - %{author}): %{message}, Build
      Time: %{duration}'
    - 'Change view : %{compare_url}'
    - 'Build details : %{build_url}'
deploy:
  provider: releases
  api_key:
    secure: mIuVdZ7+wsgZ/0ROnIyFVPlE7ldu+94eTUJi5m5LAgBl2VwpopBiSluf1Hzxdv/O6nL5Vir1yg0GTMc5XPSIYdgUTkJU1Rw4qd2EDVV+ajlB9k00yhggTAT1w88iP+J5ckbZ3BMZ57euMHVCi1dNxKYTuOAxyR1gm38meYbrX7bjh6+QuRuvF9csuUmC3RGTCOt8G7XJACRjZrSe5k8x17xBiiQBd5J0RSRnDq/ThEKT6VQMzdsxuHZy+xPmgeiGhVJfYgZkBfwMDZFbLRj9E8y6yVDH4Vk+ZRVTJSb5NycOTKAJ64TqaSldxQwbkjM7p7BbTZlB3h4igAhmwJB/lCc171sDIyTX8cP6mC0dKeUJd/PLIsHTJCBoiGyjggR+2yX92bj3FJbOOYvtyUuI5HJ78paHmygsUOITmm/kcuR4Wzq3Cyg1soKHKrnxIIDwv+0utsfM85XQqvjGxOVMj+Vsx9fHPQ6Nx9nwibufQoYWbR/gOba5LbqscjligUTXh4zcLm/i4H14teW18Nrnz+EPfCL6Gllf5BhywgMo9jRU24a/BU1jJlOzgfAL4j7N6L+3jvebETqjDfR2CPIid7Z7bCF08nLqCXn0LCBZIkT7BhOMxw6cVsJCohecQGNgDo8HcmV/vRUT/4uIn7Uy5Uwq1iu7Ac4V9eI6EWMsVvI=
  file: src/komodod
  on:
    repo: ca333/dsec
