dist: xenial
language: cpp
compiler:
- gcc
before_install:
- sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
- sudo apt-get update -qq
- sudo apt-get install libgnutls28-dev
- sudo apt-get install build-essential pkg-config libcurl3-gnutls-dev libc6-dev libevent-dev
  m4 g++-multilib autoconf libtool ncurses-dev unzip git python zlib1g-dev wget bsdmainutils
  automake libssl-dev libprotobuf-dev protobuf-compiler libdb++-dev ntp ntpdate
script:
- "./zcutil/build.sh -j 5"
notifications:
  irc:
    channels:
    - chat.freenode.net#komodoplatform
    template:
    - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
    - 'Alt Message : %{repository_slug} - (%{commit} - %{author}): %{message}, Build
      Time: %{duration}'
    - 'Change view : %{compare_url}'
    - 'Build details : %{build_url}'
